name: Quality

on:
  # Trigger workflow on pull request, but only for PRs
  # merging into staging
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/*.py
          !**/migrations/*
          !**/tests/*
          !**/test*.py
          !**/urls.py
          !**/fixtures.py
          !**/envs/*
          !common/**/etree.py
        DOT: '...'
        DIFF_FILTER: 'AMRC'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: pip install -r requirements/quality.txt

    - name: Creating PyLint report
      id: pylint-report
      continue-on-error: true
      run: |
        pylint ${{ env.GIT_DIFF }} 2>&1 | tee report_pylint.txt

        body=$(cat report_pylint.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo ::set-output name=icon::":x:"
        [[ $body == *".py:"* || $body == *"***********"* ]] && title="**Please fix following pylint issues:**"
        [[ ${body:5} == "-----"* ]] && score="Good Job, Pylint Score:" && echo ::set-output name=status::success \
        && echo ::set-output name=icon::":white_check_mark:" && echo ::set-output name=value::10
        echo ::set-output name=score::$score
        echo ::set-output name=title::$title
        echo ::set-output name=body::$body
      if: env.GIT_DIFF

    - name: Creating iSort report
      id: isort-report
      continue-on-error: true
      run: |
        isort ${{ env.GIT_DIFF }} -c 2>&1 | tee report_isort.txt
        sed -i 's#/home/runner/work/ShopRaha-BE/ShopRaha-BE##g' report_isort.txt

        body=$(cat report_isort.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"

        echo ::set-output name=icon::":x:"
        title="**Please fix following iSort issues:**"
        [[ ${#body} == 0 ]] && echo ::set-output name=icon::":white_check_mark:" && \
        echo ::set-output name=status::success || (body="\`\`\` %0A $body %0A \`\`\`" \
        && echo ::set-output name=title::$title && echo ::set-output name=body::$body)
      if: env.GIT_DIFF

    - name: Post report on PR
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          **pylint:** ${{ steps.pylint-report.outputs.icon }}
          ${{ steps.pylint-report.outputs.title }}
          ```
          ${{ steps.pylint-report.outputs.score }}${{ steps.pylint-report.outputs.body }}
          ```
          
          **iSort:** ${{ steps.isort-report.outputs.icon }}
          ${{ steps.isort-report.outputs.title }}
          ${{ steps.isort-report.outputs.body }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
      if: env.GIT_DIFF


    - name: No py file, post comment on PR
      uses: mshick/add-pr-comment@v1
      with:
        message: |
            No python file from included pattern in this PR . **Looks good** :+1:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
      if: env.GIT_DIFF == ''

    - name: Check pylint score

      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Pylint score is not up to the mark! Report-value= ${{ steps.pylint-report.outputs.value }}')
      if: ${{ env.GIT_DIFF != '' && steps.pylint-report.outputs.value != 10 }}

    - name: Check isort report

      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Isort report has error(s), please fix!')
      if: ${{ env.GIT_DIFF != '' && contains(steps.isort-report.outputs.body, 'ERROR:') }}
